//get and post request
export const PRODUCT_REQUEST="PRODUCT_REQUEST"

export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"

export const PRODUCT_FAILURE="PRODUCT_FAILURE"

export const POST_PRODUCT_SUCCESS="POST_PRODUCT_RSUCCESS"


//Patch

export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS"


//Auth action
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"